version: "3.8"
name: books-service

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:chevas@db:5432/booksdb?sslmode=disable"
      DATABASE_MIGRATIONS_PATH: "/src/migrations"
      SERVICE_SHUTDOWN_TIMEOUT: "10s"
      HTTP_REQUEST_TIMEOUT: "5s"
      NOTIFICATIONS_TIMEOUT: "5s"
      ENABLE_NOTIFICATIONS: "true"
      SERVER_WAITS_NOTIFICATIONS_TIMEOUT: "2s"
      NOTIFICATIONS_BASE_URL: "https://ntfy.sh/A3luOh46"
      
  db:
    image: postgres:14.6-bullseye
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_PASSWORD: chevas
      POSTGRES_DB: booksdb
    ports: 
      - "5000:5432"
