version: "3.8"
name: books-service-test

services:
  db:
    image: postgres:14.6-bullseye
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: booksdb
    ports: 
      - "5432:5432"
