version: "3.8"
name: books-service

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:chevas@db:5432/booksdb?sslmode=disable"
      DATABASE_MIGRATIONS_PATH: "/src/migrations"
      SERVICE_SHUTDOWN_TIMEOUT: "10s"
      HTTP_REQUEST_TIMEOUT: "5s"
      NOTIFICATIONS_TIMEOUT: "5s"
      ENABLE_NOTIFICATIONS: "true"
      SERVER_WAITS_NOTIFICATIONS_TIMEOUT: "2s"
      NOTIFICATIONS_BASE_URL: "https://ntfy.sh/A3luOh46"
