# fly.toml file generated for books-service on 2023-05-30T15:13:30-03:00

app = "books-service"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[env]
  DATABASE_MIGRATIONS_PATH = "/src/migrations"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
